mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining-dockeragent', '0.0.16'
mod 'puppetlabs-docker', '3.5.0'
mod 'puppetlabs-translate', '1.2.0'
mod 'puppetlabs-apt', '7.0.1'
mod 'puppetlabs-powershell', '2.3.0'
mod 'puppetlabs-reboot', '2.1.2'
